
---
- name: This is to install httpd
  hosts: Dev
  become: yes
  gather_facts: yes
  tasks:
   - name: install httpd
     ansible.builtin.yum:
       name: httpd
       state: latest
   - name: start apache
     ansible.builtin.service:
       name: httpd
       state: started
   - name: Copy file
      copy:
        src: /var/lib/jenkins/workspace/${JOB_NAME}/index.html
        dest: /var/www/html/


